### ISSUE TITLE
Project Files Removed?

### ISSUE THREAD

**Issue by dgdosen** [blockstack/blockstack-ios-client#1]
That makes it a bit difficult to build and install a client :)  Any idea why?

**Comment by SynapseIX** [comment]
Hey @dgdosen, I'm completely revamping the client and will push the new files again later today. The previous code had lots of issues because of transient dependencies caused by CoreBitcoin in Swift and instead of trying to fix that, it was easier to just recreate everything. It's still in its infancy, so it wasn't a big of a deal to re-make it. More info on this can be found on the Blockstack Slack, channel #mobile.

**Comment by SynapseIX** [comment]
Files re-added + all Onename API operations are now supported.
